### ISSUE TITLE
latest orb maven version for Set Up Project 

### ISSUE THREAD

**Issue by enjoeyland** [CircleCI-Public/maven-orb#16]
**Describe the bug**

I think version of orb maven is wrong.
`orbs:
   maven: circleci/maven@0.0.12 # <== wrong version`

**To Reproduce**

Go to Project Dashboard 
click on "Set up Project"
select combo box to "Maven (Java)"

then the code appear

**Expected behavior**
from
`orbs:
  maven: circleci/maven@0.0.12`

to
`orbs:
  maven: circleci/maven@1.0.2`
or
`orbs:
  maven: circleci/maven@1.0.3`

**Additional context**
![image](https://user-images.githubusercontent.com/16879600/103086303-9efd4780-4627-11eb-957c-13031c31f177.png)

**Comment by enjoeyland** [comment]
sorry
It think this issue is not bug.. I'm first doing issuing problem..

[Additional context](https://discuss.circleci.com/t/change-tag-parameter-of-default-executor-on-orbs-maven/38614)
I'm trying to change executor tag parameter.
I read 1.0.3 (current latest) version document. I think that my problem. I should have read 0.0.12 version document..

Expected behavior
Could you update version to latest version for not confuse newcomer (like me)?

**Comment by dsayling** [comment]
@enjoeyland - We definitely understand that the orb version in the onboarding config is out-of-date, and we are working on updating many of the onboarding configs.

I have routed this specific issue to the internal team that manages the UI for setting up the project and the onboarding config. 


Now, as for setting the executor in the newest versions. [Define an executor](https://circleci.com/docs/2.0/configuration-reference/#executors-requires-version-21), here's a machine example. And then reference the executor in the config. This should be a working example.

```yaml
version: 2.1
orbs:
  maven: circleci/maven@1.1
executors:
  example:
    docker:
      - image: cimg/openjdk:13.0
workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: example
```

If you want to update the version of openjdk, you can update the `- image: cimg/openjdk` tag to anything [here](https://circleci.com/developer/images/image/cimg/openjdk).
