### ISSUE TITLE
Version 1.2.0 seems to ignore the settings_file parameter

### ISSUE THREAD

**Issue by pdumontel** [CircleCI-Public/maven-orb#20]
Not sure how to proceed or I have something set up wrong. When upgrading to 1.2.0 version of the orb, the settings_file parameter seems to be ignored, and the dependency:go-offline seems to just go to maven central.

https://app.circleci.com/pipelines/bitbucket/dbpbok/gnsearchcustomer/97/workflows/a4933db0-cdf4-4c30-9988-27a5d4f12fb0/jobs/147

Seems in 1.2.0 the $@ is set in a different step, and the verify_dependencies is set to true by default. There is no way to set this in the test job. Also, it would seem it would not be good to set it to false, as the go-offline would then not run, and no dependencies would get cached.

Using 1.1.1 seems to work as expected, i.e. the dependencies are downloaded from the repositories configured in the settings_file specified file.

**Comment by Jaryt** [comment]
Your assumption as to why this is occurring is correct. I have merged those steps in #29 to resolve this problem.
