### ISSUE TITLE
Set java version as parameter

### ISSUE THREAD

**Issue by mmarquezv** [CircleCI-Public/maven-orb#7]
**Is your feature request related to a problem? Please describe.**
Command was /bin/sh -c cd /home/circleci/project && /usr/local/jdk-13.0.2/bin/java -javaagent:/home/circleci/.m2/repository/org/jacoco/org.jacoco.agent/0.8.2/org.jacoco.agent-0.8.2-runtime.jar=destfile=/home/circleci/project/target/jacoco.exec,append=true -jar /home/circleci/project/target/surefire/surefirebooter10918340306723605993.jar /home/circleci/project/target/surefire 2020-05-20T20-11-12_463-jvmRun1 surefire16651888430480925363tmp surefire_014585002933984758648tmp

**Describe the solution you'd like**
Is there any way to configure the orb to specify java version to use?

**Describe alternatives you've considered**
None

**Additional context**
Compiled an Spring Boot with java 11

**Comment by walles** [comment]
How do I configure the orb to specify java version to use?
